# Site settings
title: Sui - Blog
email: 897970325@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Sui - Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.vmsdn.com" # the base hostname & protocol for your site
rss_url: http://wpa.qq.com/msgrd?v=3&uin=897970325&site=qq&menu=yes 

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
#twitter: masonsuyan
# weibo:    ID
github: suiblog
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: http://blog.vmsdn.com/assets/img/github.gif
favicon: http://blog.vmsdn.com/assets/img/tx.gif

# disqus 设置
#disqus:
#  shortname: suyan-zh

# google analytics 设置
#ga:
 # id: UA-54767140-1
 # url: yansu.org

# Build settings
#permalink: /:year/:month/:day/:title.html
#markdown: kramdown
#highlighter: rouge
sass:
  style: compressed
